# Site settings
title: "Stefan's Blog"
description: "This is my blog. It is about technical stuff. I like to try out lots of different things, so the topic of the posts might vary."
url: "http://stefandollase.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# About the author
author_fullname: "Stefan Dollase"
author_address: [ "Harscampstraße 22", "52062 Aachen" ]
email: "me ät stefandollase.de"
github_username: "stefandollase"

# Disqus settings
disqus_shortname: "stefandollase"
disqus_identifier_prefix: "blog:"

# Build settings
markdown: kramdown

# Page Menu Entries
menu_entries:
  - url: "/about/"
    title: "About1"
  - url: "/about/"
    title: "About2"
  - url: "/about/"
    title: "About3"
