# Site settings
title: "Stefan's Blog"
description: "This is my blog."
url: "http://blog.stefandollase.de" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

# About the author
author_fullname: "Stefan Dollase"
author_address: [ "Harscampstraße 22", "52062 Aachen" ]
email: "blog ät stefandollase.de"
github_username: "stefandollase"

# Build settings
markdown: kramdown

# Page Menu Entries
menu_entries:
  - url: "/projects/"
    title: "Projects"
  - url: "/about/"
    title: "About"
